### PR TITLE
Initial commit #109 - aws public TF plan

### PR DESCRIPTION
**Pull request by tayzlor**
Still work to do here, opening for initial feedback and if anyone else feels like completing it.
Guess this will just be used primarily for demos / test harness. Maybe we could even lower the barrier here and do away with Atlas integration?

- [ ] Test TF plan (and fix any outstanding bugs)
- [x] Add bootstrap scripts to provision on AWS
- [ ] Add docs

### CODE REVIEW

**Comment by tayzlor** [comment]
tagging tests as might be handy for an integration test with AWS.

**Comment by wallies** [comment]
This might cause you an issue
security_groups - (Optional) A list of security group IDs or names to associate with. If you are within a VPC, you'll need to use the security group ID. Otherwise, for EC2, use the security group name.

**Comment by wallies** [comment]
got it working. Only bug is when you run bootstrap/apollo-down.sh it asks for values, is this expected?

**Comment by enxebre** [comment]
"Only bug is when you run bootstrap/apollo-down.sh it asks for values" is unrelated see https://github.com/Capgemini/Apollo/pull/219/files

**Comment by enxebre** [comment]
See https://github.com/Capgemini/Apollo/pull/234

**Comment by tayzlor** [comment]
I've got the following issues - 

**AWS VPC**

- No nodes/services available in Consul UI. 

**Digitalocean** 

- No slaves Registered in Mesos
- Mesos redirect to master redirects to the hostname instead of the IP address

**Pull request merged**
