### PR TITLE
Azure provider

### PR DESCRIPTION
**Pull request by tayzlor**
Opening this up but it's still a WIP.

On the TODO - 

- [ ] Build the Azure image from Packer using https://github.com/msopentech/packer-azure and test it
- [ ] Complete the terraform scripts to reference built image and test fully the provisioning of instances in azure
- [ ] Update the terraform dynamic inventory to handle Azure
- [ ] Add docs around getting started on Azure

### CODE REVIEW

**Comment by tayzlor** [comment]
Current state of this is when deploying I receive the following error - 

* Error creating instance apollo-mesos-master-0: Error response from Azure. Code: BadRequest, Message: The certificate with thumbprint BIG_HASH was not found.

**Comment by tayzlor** [comment]
Adding a comment here so I dont forget if I come back to it - 

The packer built images seem to suffer from this issue - 

https://social.msdn.microsoft.com/Forums/azure/en-us/54c600c0-f4d6-4b20-ad87-1358fa10d27a/linux-vm-ssh-connection-refused
https://bugs.launchpad.net/ubuntu/+source/walinuxagent/+bug/1305418

Weird since we should be building on the latest ubuntu 14.04 there. Get connection refused when trying to connect to a provisioned VM (with username / pass)

**Comment by tayzlor** [comment]
A workaround for the SSH key thumbprint issues has been posted in https://github.com/hashicorp/terraform/issues/2419#issuecomment-135862402 (as well as a feature request to add support to the terraform API to upload SSH keys). In the meantime we should be able to upload the key via the workaround documented over there.

**Comment by wallies** [comment]
declining in favour of #493

**Pull request closed without merging**
