### PR TITLE
109 aws public fixes

### PR DESCRIPTION
**Pull request by enxebre**

### CODE REVIEW

**Comment by enxebre** [comment]
Fix https://github.com/Capgemini/Apollo/pull/198

**Comment by tayzlor** [comment]
Review of the code this looks good to go. I think the docs could be improved but we can fix that after. Will give it a spin from my machine when I get a chance.

**Comment by enxebre** [comment]
There is an issue with mesos master redirecting to internal ip instead of public one when looking for the master lead.

**Comment by tayzlor** [comment]
@enxebre based on your comment, this still 'needs work' ?

**Comment by enxebre** [comment]
My comment is based on a quick manual test. It needs more testing first.

**Comment by tayzlor** [comment]
just did a provision and can confirm the issue exists here too. having a look

**Comment by tayzlor** [comment]
Closing this as I merged it into #198

**Pull request closed without merging**
